### ISSUE TITLE
keep center while zooming in/zooming out

### ISSUE THREAD

**Issue by yojona** [wouterraateland/use-pan-and-zoom#17]
Is this dead? @wouterraateland 

I love how it works on version 0.1.0:
https://codesandbox.io/s/use-pan-zoom-example-forked-rnfmi?file=/src/index.js:329-345

the latest version moves the content to the right while zooming
https://codesandbox.io/s/n3rpmj60w0?file=/src/App.jsx

Is there any chance of getting a new version with this fixed? or, is it safe to use v0.1.0 on prod or is it buggy?

**Comment by wouterraateland** [comment]
Not sure why this happened. Just released a new version (0.6.1). In this version, the zooming should work as 0.1.0 again.
Closing this for now, feel free to reopen if it isn't solved for you!
